export const notificationsData = [
	{
		id: "not1",
		name: "New Booking #1001",
		time: "2 min ago",
		active: true,
	},
	{
		id: "not2",
		name: "New Booking #1002",
		time: "4 min ago",
		active: true,
	},
	{
		id: "not3",
		name: "New Booking #1003",
		time: "6 min ago",
		active: true,
	},
	{
		id: "not4",
		name: "New Booking #1004",
		time: "8 min ago",
		active: true,
	},
	{
		id: "not5",
		name: "New Booking #1005",
		time: "10 min ago",
		active: true,
	},
	{
		id: "not6",
		name: "New Booking #1006",
		time: "12 min ago",
		active: false,
	},
	{
		id: "not7",
		name: "New Booking #1007",
		time: "14 min ago",
		active: true,
	},
	{
		id: "not8",
		name: "New Booking #1008",
		time: "16 min ago",
		active: false,
	},
	{
		id: "not9",
		name: "New Booking #1009",
		time: "18 min ago",
		active: true,
	},
	{
		id: "not10",
		name: "New Booking #1010",
		time: "20 min ago",
		active: false,
	},
	{
		id: "not11",
		name: "New Booking #1011",
		time: "22 min ago",
		active: true,
	},
	{
		id: "not12",
		name: "New Booking #1012",
		time: "24 min ago",
		active: false,
	},
	{
		id: "not13",
		name: "New Booking #1013",
		time: "26 min ago",
		active: true,
	},
	{
		id: "not14",
		name: "New Booking #1014",
		time: "28 min ago",
		active: false,
	},
	{
		id: "not15",
		name: "New Booking #1015",
		time: "30 min ago",
		active: true,
	},
	{
		id: "not16",
		name: "New Booking #1016",
		time: "32 min ago",
		active: false,
	},
	{
		id: "not17",
		name: "New Booking #1017",
		time: "34 min ago",
		active: true,
	},
	{
		id: "not18",
		name: "New Booking #1018",
		time: "36 min ago",
		active: false,
	},
	{
		id: "not19",
		name: "New Booking #1019",
		time: "38 min ago",
		active: true,
	},
	{
		id: "not20",
		name: "New Booking #1020",
		time: "40 min ago",
		active: false,
	},
	{
		id: "not21",
		name: "New Booking #1021",
		time: "42 min ago",
		active: true,
	},
	{
		id: "not22",
		name: "New Booking #1022",
		time: "44 min ago",
		active: false,
	},
	{
		id: "not23",
		name: "New Booking #1023",
		time: "46 min ago",
		active: true,
	},
	{
		id: "not24",
		name: "New Booking #1024",
		time: "48 min ago",
		active: false,
	},
	{
		id: "not25",
		name: "New Booking #1025",
		time: "50 min ago",
		active: true,
	},
	{
		id: "not26",
		name: "New Booking #1026",
		time: "52 min ago",
		active: false,
	},
	{
		id: "not27",
		name: "New Booking #1027",
		time: "54 min ago",
		active: true,
	},
	{
		id: "not28",
		name: "New Booking #1028",
		time: "56 min ago",
		active: false,
	},
	{
		id: "not29",
		name: "New Booking #1029",
		time: "58 min ago",
		active: true,
	},
	{
		id: "not30",
		name: "New Booking #1030",
		time: "1 hour ago",
		active: false,
	},
	{
		id: "not31",
		name: "New Booking #1031",
		time: "1 hour ago",
		active: true,
	},
	{
		id: "not32",
		name: "New Booking #1032",
		time: "1 hour ago",
		active: false,
	},
	{
		id: "not33",
		name: "New Booking #1033",
		time: "1 hour ago",
		active: true,
	},
	{
		id: "not34",
		name: "New Booking #1034",
		time: "1 hour ago",
		active: false,
	},
	{
		id: "not35",
		name: "New Booking #1035",
		time: "2 hours ago",
		active: true,
	},
	{
		id: "not36",
		name: "New Booking #1036",
		time: "2 hours ago",
		active: false,
	},
	{
		id: "not37",
		name: "New Booking #1037",
		time: "2 hours ago",
		active: true,
	},
	{
		id: "not38",
		name: "New Booking #1038",
		time: "2 hours ago",
		active: false,
	},
	{
		id: "not39",
		name: "New Booking #1039",
		time: "2 hours ago",
		active: true,
	},
	{
		id: "not40",
		name: "New Booking #1040",
		time: "2 hours ago",
		active: false,
	},
	{
		id: "not41",
		name: "New Booking #1041",
		time: "Yesterday",
		active: true,
	},
	{
		id: "not42",
		name: "New Booking #1042",
		time: "Yesterday",
		active: false,
	},
	{
		id: "not43",
		name: "New Booking #1043",
		time: "Yesterday",
		active: true,
	},
	{
		id: "not44",
		name: "New Booking #1044",
		time: "Yesterday",
		active: false,
	},
	{
		id: "not45",
		name: "New Booking #1045",
		time: "Yesterday",
		active: true,
	},
	{
		id: "not46",
		name: "New Booking #1046",
		time: "Yesterday",
		active: false,
	},
	{
		id: "not47",
		name: "New Booking #1047",
		time: "Yesterday",
		active: true,
	},
	{
		id: "not48",
		name: "New Booking #1048",
		time: "Yesterday",
		active: false,
	},
	{
		id: "not49",
		name: "New Booking #1049",
		time: "Yesterday",
		active: true,
	},
	{
		id: "not50",
		name: "New Booking #1050",
		time: "Yesterday",
		active: false,
	},
];
